name: cd
on:
    push:
      branches: [main]
jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
      
            - name: Set up Go
              uses: actions/setup-go@v5
            
            - name: Install Goose
              run: go install github.com/pressly/goose/v3/cmd/goose@latest
            
            - name: migrate database
              env:
                DATABASE_URL: ${{ secrets.DATABASE_URL }}
              run: scripts/migrateup.sh

            - name: Deploy
              run: scripts/buildprod.sh

            - name: Finish assignment
              run: gcloud builds submit
              continue-on-error: true